### PR TITLE
nimble/phy/nrf: Fix build with GCC 11.1

### PR DESCRIPTION
**Pull request by sjanc**
Looks like GCC 11.1 doesn't like current code. The looks OK though...

Error: repos/apache-mynewt-nimble/nimble/drivers/nrf52/src/ble_hw.c: In
    function 'ble_hw_get_static_addr':
repos/apache-mynewt-nimble/nimble/drivers/nrf52/src/ble_hw.c:118:9: error:
    'memcpy' offset [0, 3] is out of the bounds [0, 0] [-Werror=array-bounds]
  118 |         memcpy(addr->val, (void *)&NRF_FICR->DEVICEADDR[0], 4);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repos/apache-mynewt-nimble/nimble/drivers/nrf52/src/ble_hw.c:119:9: error:
   'memcpy' offset [0, 1] is out of the bounds [0, 0] [-Werror=array-bounds]
  119 |         memcpy(&addr->val[4], (void *)&NRF_FICR->DEVICEADDR[1], 2);

### CODE REVIEW

**Comment by sjanc** [comment]
it is a bit of an RFC as this seems to be issue on compiler side

**Review by kasjer — APPROVED** [review]
LGTM

**Comment by utzig** [comment]
## Style check summary

#### No suggestions at this time!
